# Generated by Django 3.2.13 on 2023-08-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20230817_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
