# Generated by Django 3.2.13 on 2023-08-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems_1',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
