# Generated by Django 3.2.13 on 2023-08-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_orderitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItems_1',
        ),
    ]
