# Generated by Django 3.2.13 on 2023-08-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_delete_orderitems_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
