# Generated by Django 3.2.13 on 2023-08-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
