# Generated by Django 3.2.13 on 2023-08-19 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_brands_categories_orderitems_orders_products_staffs_stocks_stores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.products')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.stores')),
            ],
            options={
                'db_table': 'stocks',
                'unique_together': {('store', 'product')},
            },
        ),
    ]
